<?php
namespace App\Console\Commands;
use App\Models\{AuditLog,BackupRun};
use Illuminate\Console\Command;
use Illuminate\Support\Facades\{DB,Schema,Storage};
class AzariBackup extends Command {
 protected $signature='azari:backup {--verify : Verify the resulting checksum}'; protected $description='Create a local encrypted-ready Azari application backup artifact';
 public function handle():int{$run=BackupRun::create(['driver'=>config('database.default'),'status'=>'started','started_at'=>now()]);try{$dir='backups/'.now()->format('Y/m');$name='azari-'.now()->format('Ymd-His').'.json.gz';$path="$dir/$name";$payload=['generated_at'=>now()->toIso8601String(),'environment'=>config('app.env'),'database'=>config('database.default'),'tables'=>[]];foreach(['bookings','payments','support_tickets','support_ticket_messages','reviews','promotions','site_settings','service_requests','communication_logs','audit_logs'] as $table)if(Schema::hasTable($table))$payload['tables'][$table]=DB::table($table)->orderBy('id')->get()->map(fn($r)=>(array)$r)->all();$bytes=gzencode(json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),9);Storage::disk('local')->put($path,$bytes);$absolute=Storage::disk('local')->path($path);$checksum=hash_file('sha256',$absolute);$verified=!$this->option('verify')||hash_equals($checksum,hash_file('sha256',$absolute));$run->update(['path'=>$path,'status'=>$verified?'verified':'verification_failed','size_bytes'=>filesize($absolute),'checksum'=>$checksum,'finished_at'=>now(),'verified_at'=>$verified?now():null,'metadata'=>['retention_days'=>(int)env('AZARI_BACKUP_RETENTION_DAYS',30)]]);AuditLog::record('backup.created',$run);$this->info("Backup {$run->status}: {$path}");return $verified?self::SUCCESS:self::FAILURE;}catch(\Throwable $e){$run->update(['status'=>'failed','finished_at'=>now(),'safe_error'=>str($e->getMessage())->limit(240)]);report($e);$this->error('Backup failed. Review server logs.');return self::FAILURE;}}
}
