@extends('admin.layouts.app')
@section('content')
<div class="az-premium-page-head"><div><span class="az-premium-kicker">{{ $listing->reference }}</span><h1>{{ data_get($listing->property_data,'name') }}</h1><p>Submitted by {{ $listing->user->name }} · {{ $listing->user->email }} · {{ $listing->user->phone }}</p></div><a class="az-premium-button" href="{{ route('azari.admin.owner-listings.agreement',$listing) }}">Download agreement</a></div>
<div class="az-s78-grid">
<section class="az-premium-card"><div class="az-premium-card-head"><div><h2>Property data</h2><p>Same field names used by the admin inventory form.</p></div></div><dl class="az-s78-detail">@foreach($listing->property_data as $key=>$value)@if(!is_array($value))<div><dt>{{ str($key)->replace('_',' ')->title() }}</dt><dd>{{ is_bool($value)?($value?'Yes':'No'):$value }}</dd></div>@endif @endforeach<div><dt>Amenities</dt><dd>{{ $amenities->join(', ') ?: 'None selected' }}</dd></div></dl></section>
<section class="az-premium-card"><div class="az-premium-card-head"><div><h2>Owner verification</h2></div></div><dl class="az-s78-detail"><div><dt>Full name</dt><dd>{{ $listing->user->name }}</dd></div><div><dt>Phone</dt><dd>{{ $listing->user->phone ?: 'Not provided' }}</dd></div><div><dt>Identification</dt><dd>{{ $listing->user->currentIdentity?'On file':'Missing' }}</dd></div><div><dt>Agreement signed</dt><dd>{{ $listing->agreement->signed_at->format('d M Y H:i') }}</dd></div><div><dt>Proposed owner share</dt><dd>{{ number_format((float)$listing->proposed_owner_share_percentage,2) }}%</dd></div></dl></section>
</div>
@if(in_array($listing->status,['submitted','under_review']))
<div class="az-s78-grid" style="margin-top:18px">
<form class="az-premium-card az-s78-form" method="POST" action="{{ route('azari.admin.owner-listings.approve',$listing) }}">@csrf<div class="az-premium-card-head"><div><h2>Approve</h2><p>One click creates the live inventory property from the submitted values.</p></div></div><label class="az-s78-field"><span>Approved owner share (%)</span><input type="number" step=".01" min="0" max="100" name="approved_owner_share_percentage" value="{{ old('approved_owner_share_percentage',$listing->proposed_owner_share_percentage) }}" required></label><label class="az-s78-check"><input type="checkbox" name="publish_now" value="1" checked><span>Publish immediately</span></label><label class="az-s78-check"><input type="checkbox" name="feature_now" value="1"><span>Feature on homepage</span></label><label class="az-s78-field"><span>Internal notes</span><textarea name="admin_notes"></textarea></label><button class="az-premium-button">Approve and add to inventory</button></form>
<form class="az-premium-card az-s78-form" method="POST" action="{{ route('azari.admin.owner-listings.decline',$listing) }}">@csrf<div class="az-premium-card-head"><div><h2>Decline</h2><p>The owner sees the reason and can correct and resubmit.</p></div></div><label class="az-s78-field"><span>Decline reason</span><textarea name="decline_reason" required minlength="10"></textarea></label><label class="az-s78-field"><span>Internal notes</span><textarea name="admin_notes"></textarea></label><button class="az-premium-button" style="background:#8b3036">Decline listing</button></form>
</div>
@endif
@endsection
