<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payment receipt {{ $payment->reference }}</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f1ea;color:#182820;font-family:Arial,sans-serif}.toolbar,.receipt{width:min(820px,calc(100% - 32px));margin:22px auto}.toolbar{display:flex;justify-content:flex-end}.toolbar button{border:0;border-radius:10px;background:#183d33;color:#fff;padding:13px 18px;font-weight:800}.receipt{background:#fff;border:1px solid #ded8cd;padding:42px}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #183d33;padding-bottom:22px}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.15em;text-transform:uppercase;color:#aa7d35}h1{margin:7px 0 0}.status{font-weight:800;text-transform:uppercase}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:24px}.card{border:1px solid #e1ddd5;padding:17px}.card span{display:block;color:#6f7772;font-size:12px;margin-bottom:7px}.card strong{overflow-wrap:anywhere}.amount{margin-top:22px;padding:22px;background:#f1f5f3;display:flex;justify-content:space-between;align-items:center}.amount strong{font-size:24px}.note{margin-top:24px;padding:17px;border-left:4px solid #b98b3b;background:#fbf8f1;line-height:1.6}.foot{margin-top:28px;color:#6f7772;font-size:12px}@media(max-width:620px){.receipt{padding:24px}.head,.grid{display:grid;grid-template-columns:1fr}}@media print{body{background:#fff}.toolbar{display:none}.receipt{border:0;width:100%;margin:0;padding:12mm}}</style></head><body>
<div class="toolbar"><button onclick="window.print()">Print or save PDF</button></div>
<main class="receipt">
<header class="head"><div><div class="eyebrow">Azari Residences</div><h1>Payment receipt</h1></div><div class="status">{{ ucwords(str_replace('_',' ',$payment->status)) }}</div></header>
@if($fullAccess)
<section class="grid"><div class="card"><span>Booking reference</span><strong>{{ $booking->reference }}</strong></div><div class="card"><span>Payment reference</span><strong>{{ $payment->reference }}</strong></div><div class="card"><span>Residence</span><strong>{{ $booking->property?->name ?? 'Azari Residence' }}</strong></div><div class="card"><span>Payment date</span><strong>{{ ($payment->paid_at ?: $payment->created_at)?->format('d M Y, H:i') }}</strong></div></section>
@else
<section class="grid"><div class="card"><span>Booking reference</span><strong>{{ $booking->reference }}</strong></div><div class="card"><span>Payment reference</span><strong>{{ $payment->reference }}</strong></div></section>
@endif
<div class="amount"><span>Amount {{ $payment->isSuccessful() ? 'paid' : 'recorded' }}</span><strong>{{ $payment->currency }} {{ number_format((float)$payment->amount,2) }}</strong></div>
@unless($fullAccess)<div class="note">This limited receipt is shown because the payment was made for another person's booking or the payer was not signed in to the account that owns the booking. It confirms the payment reference and amount without exposing private reservation information.</div>@endunless
<footer class="foot">Generated {{ now()->format('d M Y, H:i') }}</footer>
</main></body></html>
