@extends('layouts.user')
@section('title','Booking '.$booking->reference)
@section('kicker','Booking details')
@section('page_title',$booking->reference)
@section('content')
@php($successful=$booking->payments->firstWhere('status','successful'))
@php($latestPayment=$booking->payments->sortByDesc('created_at')->first())
<section class="az-user-detail-grid">
<div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Reservation</h2><p class="az-user-panel-subtitle">{{ $booking->property?->name ?? 'Azari Residence' }}</p></div><span class="az-user-status">{{ str_replace('_',' ',$booking->status) }}</span></header><div class="az-user-panel-body"><dl class="az-user-detail-list">
<div class="az-user-detail-row"><dt>Booking reference</dt><dd>{{ $booking->reference }}</dd></div><div class="az-user-detail-row"><dt>Property</dt><dd>{{ $booking->property?->name }}</dd></div><div class="az-user-detail-row"><dt>Unit or room</dt><dd>{{ $booking->property?->unit_number ?: $booking->property?->code }}</dd></div><div class="az-user-detail-row"><dt>Adults / children</dt><dd>{{ $booking->adults }} / {{ $booking->children }}</dd></div><div class="az-user-detail-row"><dt>Number of nights</dt><dd>{{ $booking->nights }}</dd></div>@if($booking->checked_in_at)<div class="az-user-detail-row"><dt>Checked in at</dt><dd><x-user-local-time :value="$booking->checked_in_at" /></dd></div>@else<div class="az-user-detail-row"><dt>Scheduled arrival</dt><dd>{{ $booking->check_in?->format('j F Y') }}</dd></div>@endif@if($booking->completed_at)<div class="az-user-detail-row"><dt>Checked out at</dt><dd><x-user-local-time :value="$booking->completed_at" /></dd></div>@else<div class="az-user-detail-row"><dt>Scheduled departure</dt><dd>{{ $booking->check_out?->format('j F Y') }}</dd></div>@endif
</dl></div></div>
<div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Charges and payment</h2><p class="az-user-panel-subtitle">Financial amounts remain tied to this booking</p></div></header><div class="az-user-panel-body"><dl class="az-user-detail-list"><div class="az-user-detail-row"><dt>Nightly/subtotal</dt><dd>{{ $booking->currency }} {{ number_format((float)$booking->subtotal,2) }}</dd></div><div class="az-user-detail-row"><dt>Add-ons</dt><dd>{{ $booking->currency }} {{ number_format((float)$booking->add_on_total,2) }}</dd></div><div class="az-user-detail-row"><dt>Fees</dt><dd>{{ $booking->currency }} {{ number_format((float)$booking->fee_total,2) }}</dd></div><div class="az-user-detail-row"><dt>Tax</dt><dd>{{ $booking->currency }} {{ number_format((float)$booking->tax_total,2) }}</dd></div><div class="az-user-detail-row"><dt>Total</dt><dd>{{ $booking->currency }} {{ number_format((float)$booking->total,2) }}</dd></div><div class="az-user-detail-row"><dt>Verified paid</dt><dd>{{ $booking->currency }} {{ number_format($booking->successfulPaymentsTotal(),2) }}</dd></div><div class="az-user-detail-row"><dt>Balance</dt><dd>{{ $booking->currency }} {{ number_format($booking->balanceDue(),2) }}</dd></div><div class="az-user-detail-row"><dt>Payment status</dt><dd>{{ str_replace('_',' ',$latestPayment?->status ?? 'not started') }}</dd></div><div class="az-user-detail-row"><dt>Gateway</dt><dd>{{ $latestPayment ? ucfirst($latestPayment->provider) : 'Not yet selected' }}</dd></div></dl>@if($booking->balanceDue()>0)<div class="az-user-actions" style="margin-top:18px"><a class="az-user-button az-user-button--primary" href="{{ route('public.payment.select',$booking->reference) }}">Pay securely</a></div>@endif</div></div>
</section>
<section class="az-user-detail-grid" style="margin-top:18px">
<div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Guests and identities</h2><p class="az-user-panel-subtitle">Every additional adult must have an identity attached</p></div></header><div class="az-user-panel-body"><div class="az-user-list">@foreach($booking->guests as $guest)@php($identity=$guest->identityLink?->userIdentityDocument ?: $guest->identityDocument)<div class="az-user-list-item"><div><h3>{{ $guest->full_name }} {{ $guest->is_lead?'(booking owner)':'' }}</h3><p>{{ ucfirst($guest->type) }} · {{ $identity ? 'Identity attached' : ($guest->type==='child'?'No ID required':'Identity required') }}</p></div><span class="az-user-status {{ !$identity&&$guest->type==='adult'?'az-user-status--warning':'' }}">{{ $identity ? 'Ready' : 'Pending' }}</span></div>@endforeach</div></div></div>
<div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Linked activity</h2><p class="az-user-panel-subtitle">Documents, service requests and support remain booking-specific</p></div></header><div class="az-user-panel-body az-user-list"><a class="az-user-list-item" href="{{ route('user.payments.index') }}"><div><h3>Payments</h3><p>{{ $booking->payments_count }} payment record(s)</p></div><span class="material-symbols-outlined">chevron_right</span></a><a class="az-user-list-item" href="{{ route('user.documents.index') }}"><div><h3>Receipts & invoices</h3><p>{{ $successful ? 'Receipt available; full PDF documents arrive in Sprint 9.' : 'Available after successful payment.' }}</p></div><span class="material-symbols-outlined">chevron_right</span></a><a class="az-user-list-item" href="{{ route('user.service-requests') }}"><div><h3>Service requests</h3><p>Booking-linked workflow is scheduled for the services sprint.</p></div><span class="material-symbols-outlined">chevron_right</span></a><a class="az-user-list-item" href="{{ route('user.support-tickets') }}"><div><h3>Support tickets</h3><p>Contact Azari now; full ticketing is scheduled for Sprint 13.</p></div><span class="material-symbols-outlined">chevron_right</span></a></div></div>
</section>
<section class="az-user-panel" style="margin-top:18px"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Booking timeline</h2><p class="az-user-panel-subtitle">Only events that actually happened are displayed</p></div></header><div class="az-user-panel-body az-user-list">@foreach($timeline as $event)<div class="az-user-list-item"><div><h3>{{ str_replace('_',' ',$event->status ?? $event->to_status ?? 'Booking updated') }}</h3><p><x-user-local-time :value="$event->created_at" /></p></div></div>@endforeach@if($timeline->isEmpty())<div class="az-user-list-item"><div><h3>Booking created</h3><p><x-user-local-time :value="$booking->created_at" /></p></div></div>@endif{{ $timeline->links() }}</div></section>
@endsection
