@extends('layouts.user')
@section('title','My identity')
@section('kicker','Secure guest identity')
@section('page_title','My identity')
@section('content')
<section class="az-user-detail-grid"><div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Current government ID</h2><p class="az-user-panel-subtitle">Stored privately with no public file URL</p></div>@if($currentIdentity)<span class="az-user-status">{{ $currentIdentity->review_status }}</span>@endif</header><div class="az-user-panel-body">@if($currentIdentity)<dl class="az-user-detail-list"><div class="az-user-detail-row"><dt>Type</dt><dd>{{ $currentIdentity->identityType?->name ?? str_replace('_',' ',$currentIdentity->document_type) }}</dd></div><div class="az-user-detail-row"><dt>File</dt><dd>{{ $currentIdentity->original_name }}</dd></div><div class="az-user-detail-row"><dt>Uploaded</dt><dd><x-user-local-time :value="$currentIdentity->created_at" mode="date" /></dd></div><div class="az-user-detail-row"><dt>Review</dt><dd>{{ ucfirst($currentIdentity->review_status) }}</dd></div></dl><div class="az-user-actions" style="margin-top:18px"><a class="az-user-button az-user-button--light" href="{{ route('user.identity.download',$currentIdentity) }}">Authenticated download</a></div>@else<div class="az-user-empty"><span class="material-symbols-outlined">badge</span><p>No identity is currently on file.</p></div>@endif</div></div>
<div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">{{ $currentIdentity?'Replace identity':'Upload identity' }}</h2><p class="az-user-panel-subtitle">Passport, national ID, driver's licence or approved government ID</p></div></header><form class="az-user-panel-body" method="POST" action="{{ route('user.identity.store') }}" enctype="multipart/form-data">@csrf<div class="az-user-form-grid"><div class="az-user-field az-user-field--full"><label for="identity_type_id">Identity type</label><select id="identity_type_id" name="identity_type_id" required><option value="">Choose identity type</option>@foreach($identityTypes as $type)<option value="{{ $type->id }}" @selected(old('identity_type_id')==$type->id)>{{ $type->name }}</option>@endforeach</select></div><div class="az-user-field az-user-field--full az-user-upload"><label for="identity_document">Government ID file</label><input id="identity_document" type="file" name="document" accept=".jpg,.jpeg,.png,.webp,.pdf" required><span class="az-user-help">JPG, PNG, WEBP or PDF. Maximum 10 MB. No OCR, facial recognition or automated approval is performed.</span></div></div><button class="az-user-button az-user-button--dark" type="submit" style="margin-top:16px">Store securely</button></form></div></section>
<section class="az-user-panel" style="margin-top:18px"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Replacement history</h2><p class="az-user-panel-subtitle">Previous records remain protected for audit purposes</p></div></header><div class="az-user-panel-body">@if($history->isEmpty())<div class="az-user-empty"><p>No upload history.</p></div>@else<div class="az-user-table-wrap"><table class="az-user-table"><thead><tr><th>Type</th><th>File</th><th>Status</th><th>Current</th><th>Uploaded</th></tr></thead><tbody>@foreach($history as $document)<tr><td>{{ $document->identityType?->name ?? $document->document_type }}</td><td>{{ $document->original_name }}</td><td>{{ $document->review_status }}</td><td>{{ $document->is_current?'Yes':'Replaced' }}</td><td>{{ $document->created_at?->format('j M Y') }}</td></tr>@endforeach</tbody></table></div>{{ $history->links() }}@endif</div></section>
@endsection
