@extends('admin.layouts.app')
@section('title','Payments')
@section('content')
<section class="az-page-heading"><div><p class="az-eyebrow">Financial operations</p><h1>Payments</h1><p>Provider, callback, webhook and manually linked payment history. Ten records per page.</p></div><div class="az-s78-actions"><a class="az-button az-button--secondary" href="{{ route('azari.admin.payments.providers') }}">Provider status</a><a class="az-button az-button--primary" href="{{ route('azari.admin.payments.create') }}">Link external payment</a></div></section>
<form class="az-s78-toolbar" method="GET"><label class="az-s78-field"><span>Status</span><select name="status"><option value="">All</option>@foreach(['initiated','pending','successful','successful_excess','failed','abandoned','invalid'] as $value)<option value="{{ $value }}" @selected(request('status')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></label><label class="az-s78-field"><span>Provider</span><select name="provider"><option value="">All</option>@foreach(['flutterwave','pesapal','intouch','manual'] as $value)<option value="{{ $value }}" @selected(request('provider')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></label><label class="az-s78-field"><span>Booking</span><input name="booking" value="{{ request('booking') }}" placeholder="AZR-..."></label><label class="az-s78-field"><span>User</span><input name="user" value="{{ request('user') }}" placeholder="Name or email"></label><label class="az-s78-field"><span>Currency</span><input name="currency" value="{{ request('currency') }}" maxlength="3"></label><label class="az-s78-field"><span>From</span><input type="date" name="date_from" value="{{ request('date_from') }}"></label><label class="az-s78-field"><span>To</span><input type="date" name="date_to" value="{{ request('date_to') }}"></label><label class="az-s78-field"><span>Min amount</span><input type="number" step="0.01" name="amount_min" value="{{ request('amount_min') }}"></label><label class="az-s78-field"><span>Max amount</span><input type="number" step="0.01" name="amount_max" value="{{ request('amount_max') }}"></label><button class="az-button az-button--primary" type="submit">Filter</button></form>
<div class="az-s78-table-wrap"><table class="az-s78-table"><thead><tr><th>Reference</th><th>Booking</th><th>Guest / user</th><th>Provider</th><th>Amount</th><th>Status</th><th>Paid</th><th>Created</th><th></th></tr></thead><tbody>@forelse($payments as $payment)<tr><td><strong>{{ $payment->reference }}</strong><small>{{ $payment->provider_reference }}</small></td><td>{{ $payment->booking?->reference }}<small>{{ $payment->booking?->property?->name }}</small></td><td>{{ $payment->user?->name ?? $payment->booking?->guest_name }}<small>{{ $payment->user?->email ?? $payment->guest_email }}</small></td><td>{{ ucfirst($payment->provider) }}</td><td>{{ $payment->currency }} {{ number_format((float)$payment->amount,2) }}</td><td><span class="az-s78-badge {{ in_array($payment->status,['failed','invalid'],true)?'is-danger':($payment->status!=='successful'?'is-warning':'') }}">{{ $payment->status }}</span></td><td>{{ $payment->paid_at?->format('d M Y H:i') ?: '—' }}</td><td>{{ $payment->created_at?->format('d M Y H:i') }}</td><td><a class="az-button az-button--secondary" href="{{ route('azari.admin.payments.show',$payment) }}">View</a></td></tr>@empty<tr><td colspan="9" class="az-s78-empty">No payment records matched the filters.</td></tr>@endforelse</tbody></table></div>
<div class="az-admin-pagination">
    <span>Showing {{ $payments->firstItem() ?? 0 }}–{{ $payments->lastItem() ?? 0 }} of {{ method_exists($payments, 'total') ? $payments->total() : $payments->count() }} payments</span>
    {{ $payments->onEachSide(1)->links() }}
</div>
@endsection
