<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  if (!Schema::hasTable('support_tickets')) Schema::create('support_tickets',function(Blueprint $t){$t->id();$t->string('reference')->unique();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('booking_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->string('category');$t->string('subject');$t->string('status')->default('open');$t->string('priority')->default('normal');$t->timestamp('escalated_at')->nullable();$t->timestamp('resolved_at')->nullable();$t->timestamp('closed_at')->nullable();$t->timestamps();$t->index(['status','priority']);});
  if (!Schema::hasTable('support_ticket_messages')) Schema::create('support_ticket_messages',function(Blueprint $t){$t->id();$t->foreignId('support_ticket_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->longText('body');$t->boolean('internal')->default(false);$t->string('attachment_path')->nullable();$t->string('attachment_name')->nullable();$t->timestamps();});
  if (!Schema::hasTable('reviews')) Schema::create('reviews',function(Blueprint $t){$t->id();$t->foreignId('booking_id')->unique()->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->unsignedTinyInteger('rating');$t->string('title')->nullable();$t->text('body');$t->string('status')->default('pending');$t->boolean('featured')->default(false);$t->text('admin_reply')->nullable();$t->foreignId('moderated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('moderated_at')->nullable();$t->timestamps();$t->index(['status','featured']);});
  if (!Schema::hasTable('promotions')) Schema::create('promotions',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->string('type')->default('promotion');$t->text('summary')->nullable();$t->longText('body')->nullable();$t->string('cta_label')->nullable();$t->string('cta_url')->nullable();$t->string('image_path')->nullable();$t->boolean('is_active')->default(false);$t->boolean('is_featured')->default(false);$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->timestamps();$t->index(['is_active','type']);});
  if (!Schema::hasTable('scheduled_task_runs')) Schema::create('scheduled_task_runs',function(Blueprint $t){$t->id();$t->string('task');$t->string('status');$t->timestamp('started_at');$t->timestamp('finished_at')->nullable();$t->unsignedInteger('duration_ms')->nullable();$t->text('summary')->nullable();$t->timestamps();$t->index(['task','status']);});
 }
 public function down(): void {Schema::dropIfExists('scheduled_task_runs');Schema::dropIfExists('promotions');Schema::dropIfExists('reviews');Schema::dropIfExists('support_ticket_messages');Schema::dropIfExists('support_tickets');}
};