@extends('layouts.user')
@section('title','Security')
@section('kicker','Account protection')
@section('page_title','Security')
@section('content')
<section class="az-user-detail-grid"><div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Password</h2><p class="az-user-panel-subtitle">Use the existing secure password update flow</p></div></header><div class="az-user-panel-body"><a class="az-user-button az-user-button--dark" href="{{ route('profile.edit') }}#update-password">Change password</a></div></div><div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Account status</h2><p class="az-user-panel-subtitle">Verification and access class</p></div></header><div class="az-user-panel-body"><dl class="az-user-detail-list"><div class="az-user-detail-row"><dt>Email verification</dt><dd>{{ auth()->user()->hasVerifiedEmail()?'Verified':'Required' }}</dd></div><div class="az-user-detail-row"><dt>Account type</dt><dd>Normal user</dd></div><div class="az-user-detail-row"><dt>Operational timezone</dt><dd>{{ config('azari.timezone','Africa/Lagos') }}</dd></div></dl></div><div class="az-pagination-block">{{ $sessions->onEachSide(1)->links() }}</div></div></section>
<section class="az-user-panel" style="margin-top:18px"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Active sessions</h2><p class="az-user-panel-subtitle">Available when the application uses database-backed sessions</p></div></header><div class="az-user-panel-body">@if($sessions->isEmpty())<div class="az-user-empty"><span class="material-symbols-outlined">devices</span><p>No database session records are available under the current session driver.</p></div>@else<div class="az-user-list">@foreach($sessions as $session)<div class="az-user-list-item"><div><h3>{{ $session->ip_address ?? 'Unknown address' }}</h3><p>{{ Str::limit($session->user_agent ?? 'Unknown device',100) }} · Last active {{ \Carbon\Carbon::createFromTimestamp($session->last_activity)->diffForHumans() }}</p></div>@if($session->id!==request()->session()->getId())<form method="POST" action="{{ route('user.security.sessions.destroy',$session->id) }}">@csrf @method('DELETE')<button class="az-user-button az-user-button--danger" type="submit">End session</button></form>@else<span class="az-user-status">Current</span>@endif</div>@endforeach</div>@endif</div></section>
<x-azari-pagination-stack :items="get_defined_vars()" />
@endsection
