@extends('layouts.user')
@section('title','Payment '.$payment->reference)
@section('kicker','Payment details')
@section('page_title',$payment->reference)
@section('content')
<section class="az-user-detail-grid"><div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Payment summary</h2><p class="az-user-panel-subtitle">Safe customer-visible information only</p></div><span class="az-user-status {{ $payment->status==='failed'?'az-user-status--danger':($payment->status!=='successful'?'az-user-status--warning':'') }}">{{ $payment->status }}</span></header><div class="az-user-panel-body"><dl class="az-user-detail-list"><div class="az-user-detail-row"><dt>Internal reference</dt><dd>{{ $payment->reference }}</dd></div><div class="az-user-detail-row"><dt>Booking</dt><dd><a href="{{ route('user.bookings.show',$payment->booking->reference) }}">{{ $payment->booking->reference }}</a></dd></div><div class="az-user-detail-row"><dt>Provider</dt><dd>{{ ucfirst($payment->provider) }}</dd></div><div class="az-user-detail-row"><dt>Provider reference</dt><dd>{{ $payment->provider_reference ?: 'Pending' }}</dd></div><div class="az-user-detail-row"><dt>Amount</dt><dd>{{ $payment->currency }} {{ number_format((float)$payment->amount,2) }}</dd></div><div class="az-user-detail-row"><dt>Payment method</dt><dd>{{ $payment->payment_method ?: 'Reported after payment' }}</dd></div><div class="az-user-detail-row"><dt>Paid date</dt><dd><x-user-local-time :value="$payment->paid_at" empty="Not paid" /></dd></div><div class="az-user-detail-row"><dt>Receipt</dt><dd>{{ $payment->receipt_number ?: 'Available after verified success' }}</dd></div></dl>@if($payment->status === 'pending' && filled($payment->checkout_url) && $payment->initiated_at?->gt(now()->subMinutes(30)) && ! $payment->booking->isPaid())
<form method="POST" action="{{ route('user.payments.resume',$payment) }}" style="margin-top:18px">
@csrf
<button class="az-user-button az-user-button--primary" type="submit">Continue existing payment</button>
</form>
<p class="az-user-panel-subtitle">Returns to your existing payment attempt. No new charge is created.</p>
@endif
@if($payment->canRetry())<form method="POST" action="{{ route('user.payments.retry',$payment) }}" style="margin-top:18px">@csrf<button class="az-user-button az-user-button--primary" type="submit">Retry payment</button></form>@endif</div></div>
<div class="az-user-panel"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Verification history</h2><p class="az-user-panel-subtitle">Provider responses are redacted for safety</p></div></header><div class="az-user-panel-body az-user-list">@forelse($verificationAttempts as $attempt)<div class="az-user-list-item"><div><h3>{{ str_replace('_',' ',$attempt->result) }}</h3><p><x-user-local-time :value="$attempt->attempted_at" /> · Provider status: {{ $attempt->provider_status ?: 'Not reported' }}</p></div></div>@empty<div class="az-user-empty"><span class="material-symbols-outlined">verified_user</span><p>No verification attempt has been recorded yet.</p></div>@endforelse{{ $verificationAttempts->links() }}</div></div></section>
<section class="az-user-panel" style="margin-top:18px"><header class="az-user-panel-header"><div><h2 class="az-user-panel-title">Callback and webhook history</h2><p class="az-user-panel-subtitle">Duplicate events are acknowledged without duplicating payments</p></div></header><div class="az-user-panel-body az-user-list">@forelse($events as $event)<div class="az-user-list-item"><div><h3>{{ ucfirst($event->source) }} · {{ $event->event_type ?: 'payment event' }}</h3><p><x-user-local-time :value="$event->received_at" /> · {{ $event->processed?'Processed':'Pending' }}</p></div><span class="az-user-status {{ $event->signature_valid===false?'az-user-status--danger':'' }}">{{ $event->signature_valid===false?'Rejected':'Recorded' }}</span></div>@empty<div class="az-user-empty"><p>No callback or webhook events recorded.</p></div>@endforelse{{ $events->links() }}</div></section>
@endsection
