@extends('admin.layout') @section('title','Support tickets') @section('content')<div class="az-admin-page-head"><h1>Support tickets</h1></div><section class="az-metric-grid" aria-label="Support operational metrics">
@foreach([
    ['label'=>'Unresolved tickets', 'value'=>$metrics->unresolved ?? 0, 'icon'=>'support_agent', 'help'=>'Open or awaiting action'],
    ['label'=>'Breached SLA', 'value'=>$metrics->breached ?? 0, 'icon'=>'alarm', 'help'=>'Past due and unresolved'],
    ['label'=>'Critical incidents', 'value'=>$metrics->critical ?? 0, 'icon'=>'priority_high', 'help'=>'Safety, check-in, payment or unavailable property'],
    ['label'=>'Unassigned', 'value'=>$metrics->unassigned ?? 0, 'icon'=>'assignment_ind', 'help'=>'Unresolved and missing an assignee'],
    ['label'=>'Response overdue', 'value'=>$metrics->response_overdue ?? 0, 'icon'=>'schedule', 'help'=>'Initial reply deadline passed'],
] as $metric)
<article class="az-metric-card">
    <div class="az-metric-card__icon"><span class="material-symbols-outlined" aria-hidden="true">{{ $metric['icon'] }}</span></div>
    <div><span>{{ $metric['label'] }}</span><strong>{{ number_format((int) $metric['value']) }}</strong><small>{{ $metric['help'] }}</small></div>
</article>
@endforeach
</section><div class="az-admin-card"><form method="get"><select name="status"><option value="">All statuses</option>@foreach(['open','awaiting_staff','awaiting_guest','in_progress','escalated','resolved','closed'] as $s)<option @selected(request('status')===$s) value="{{ $s }}">{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><select name="severity"><option value="">All severities</option>@foreach(['safety','unable_to_check_in','payment_taken_no_confirmation','property_unavailable','general'] as $s)<option @selected(request('severity')===$s) value="{{ $s }}">{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><button>Filter</button></form><div class="az-admin-table-wrap"><table class="az-admin-table"><thead><tr><th>Reference</th><th>Guest</th><th>Subject</th><th>Severity</th><th>Status</th><th>SLA</th><th>Priority</th><th>Updated</th></tr></thead><tbody>@forelse($tickets as $t)<tr><td><a href="{{ route('azari.admin.support.show',$t) }}">{{ $t->reference }}</a></td><td>{{ $t->user?->name }}</td><td>{{ $t->subject }}</td><td>{{ ucwords(str_replace('_',' ',$t->severity ?? 'general')) }}</td><td>{{ $t->status }}</td><td>@if($t->sla_due_at)<span class="{{ !in_array($t->status,['resolved','closed']) && $t->sla_due_at->isPast() ? 'text-danger' : '' }}">{{ $t->sla_due_at->diffForHumans() }}</span>@else—@endif</td><td>{{ $t->priority }}</td><td>{{ $t->updated_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="8">No tickets.</td></tr>@endforelse</tbody></table></div>{{ $tickets->links() }}</div>@endsection